
services:
  redis:
    container_name: redis_container
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    # command: redis-microservices --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data

  mongodb:
    container_name: mongodb_container
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db

  mysql:
    container_name: mysql_container
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth
      MYSQL_USER: rayees
      MYSQL_PASSWORD: api
    ports:
      - 3307:3306
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql

  postgres:
    container_name: postgres_container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: api
      POSTGRES_DB: jobber_reviews
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jobber
      - RABBITMQ_DEFAULT_PASS=jobberpassword
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true"
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9300:9300
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:admin1234 http://localhost:9200/_cluster/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 12
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - default
      - elastic

  kibana-setup:
    container_name: kibana_setup_container
    image: curlimages/curl:8.13.0
    restart: "no"
    command: >
      sh -c "curl -s -u elastic:admin1234
      -X POST http://elasticsearch_container:9200/_security/user/kibana_system/_password
      -H 'Content-Type: application/json'
      -d '{\"password\":\"kibana\"}'"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.13.4
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch_container:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibana
      XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS: '["http://elasticsearch_container:9200"]'
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yaml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      kibana-setup:
        condition: service_completed_successfully
  heartbeat:
    container_name: heartbeat_container
    image: docker.elastic.co/beats/heartbeat:8.13.4
    user: root
    hostname: heartbeat
    cap_add:
      - NET_RAW
    networks:
      - elastic
    command: ["--strict.perms=false"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    depends_on: 
      - elasticsearch 
  apmServer:
    image: docker.elastic.co/apm/apm-server:8.13.4
    container_name: apm_server_container
    restart: always
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - default
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana_container:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana_container:5601
        -E apm-server.kibana.protocol=http
        -E strict.perms=false
        -E apm-server.auth.anonymous.enabled=true  
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_started
  metricbeat:
    container_name: metricbeat_container
    image: docker.elastic.co/beats/metricbeat:8.13.4
    user: root
    restart: always
    ports:
      - 5066:5066
    networks:
      - elastic
    environment:
      - DOCKER_API_VERSION=1.44
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command:
      - --strict.perms=false
      - -system.hostfs=/hostfs
    depends_on:
      - elasticsearch
  gateway:
    container_name: gateway_container
    build:
      context: ../microservices/1-gateway-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4000:4000
    env_file: ../microservices/1-gateway-service/.env
    environment:
        - ENABLE_APM=1
        - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
        - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
        - NODE_ENV=development
        - SECRET_KEY_ONE=032c5c3cfc37938ae6dd43d3a3ec7834
        - SECRET_KEY_TWO=d66e377018c0bc0b5772bbc9b131e6d9
        - CLIENT_URL=http://localhost:3000
        - AUTH_BASE_URL=http://auth_container:4002
        - USERS_BASE_URL=http://localhost:4003
        - GIG_BASE_URL=http://localhost:4004
        - MESSAGE_BASE_URL=http://localhost:4005
        - ORDER_BASE_URL=http://localhost:4006
        - REVIEW_BASE_URL=http://localhost:4007
        - REDIS_HOST=redis://redis_container:6379
        - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
        - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
        - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
  notifications:
    container_name: notification_container
    build:
      context: ../microservices/2-notification-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4001:4001
    env_file: ../microservices/2-notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - SENDER_EMAIL=turner.renner78@ethereal.email
      - SENDER_EMAIL_PASSWORD=gU6tmH2tSy6Dx1khZD
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_microservices_URL=http://apm_microservices_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
  auth:
    container_name: auth_container
    build:
      context: ../microservices/3-auth-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4002:4002
    env_file: ../microservices/3-auth-service/.env
    environment:
      - ENABLE_APM=1
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpassword@rabbitmq_container:5672
      - MYSQL_DB=mysql://rayees:api@mysql_container:3307/auth
      - CLOUD_NAME=dooaoljhe
      - CLOUD_API_KEY=944888331212822
      - CLOUD_API_SECRET=15-leSjhvJ76oQ3JLBUnSEnTkrg
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mysql
  users:
    container_name: users_container
    build:
      context: ../microservices/4-users-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4003:4003
    env_file: ../microservices/4-users-service/.env
    environment:
      - ENABLE_APM=1
      - DATABASE_URL=mongodb://mongodb_container:27017/jobber-users
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpassword@rabbitmq_container:5672
      - CLOUD_NAME=dyamr9ym3
      - CLOUD_API_KEY=385269193982147
      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
  gig:
    container_name: gig_container
    build:
      context: ../microservices/5-gig-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4004:4004
    env_file: ../microservices/5-gig-service/.env
    environment:
      - ENABLE_APM=1
      - SERVER_PORT=4004
      - DATABASE_URL=mongodb://mongodb_container:27017/jobber-gig
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - CLOUD_NAME=dyamr9ym3
      - CLOUD_API_KEY=385269193982147
      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
  chat:
    container_name: chat_container
    build:
      context: ../microservices/6-chat-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4005:4005
    env_file: ../microservices/6-chat-service/.env
    environment:
      - ENABLE_APM=1
      - DATABASE_URL=mongodb://mongodb_container:27017/jobber-chat
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - CLOUD_NAME=dyamr9ym3
      - CLOUD_API_KEY=385269193982147
      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
  order:
    container_name: order_container
    build:
      context: ../server/7-order-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4006:4006
    env_file: ../microservices/7-order-service/.env
    environment:
      - ENABLE_APM=1
      - DATABASE_URL=mongodb://mongodb_container:27017/jobber-chat
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - STRIPE_API_KEY=
      - CLOUD_NAME=dyamr9ym3
      - CLOUD_API_KEY=385269193982147
      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
  review:
    container_name: order_container
    build:
      context: ../server/8-review-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4007:4007
    env_file: ../server/8-review-service/.env
    environment:
      - ENABLE_APM=1
      - DATABASE_HOST=192.168.0.42
      - DATABASE_USER=jobber
      - DATABASE_PASSWORD=api
      - DATABASE_NAME=jobber_reviews
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
      - CLOUD_NAME=dyamr9ym3
      - CLOUD_API_KEY=385269193982147
      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - postgres
  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker-volumes/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent:
    container_name: jenkins_agent_container
    image: jenkins/ssh-agent:jdk21
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFB9ll2sKV2DpwnL/QFlkAcvLv+Xmdp1sp5lLF/geUfkV9JZRnwZ153dTxDQkKkwpvS8A7Vur0/4nChR3oqJAT2m427DIevN04HXy4EGXceSZn5OYGoIR9bukAXx9jCHOUaKQVoiI22CWsOAd5bECl18T7srqOi3+YjCQDgPQ1lbCnfztYGhHeI4SuAu0TKCdLMBYHQCT3VkNYretn1DnMyn2q9tSZnzy3NsjYkyLZ5eMH7xETgHI+aD0dzfEUgoWFF7AVlUt5aqTkdgVPROdN1GJ1k2WfRU31sLuzqRoZvclhLvZ5ME6pelxHSsWZAY6FPgMS3MzirFAYk+QP/JzYDTK5k345voYbVgO8ob+XD/prEGp4WaiYt0m3w97+K6TQL/mUUxPSCBD427MzzYuJAkeQ1I96jxWBHKWuKKESkhwuT5RjBqsVY43FAeFCmpOiI3wxws9lp2a6jzg6AYG+e4TWejHwySsmCIsXiBGqV7D8vADoTSE8QAImWIheeDU= abit@DESKTOP-G7M4262


networks:
  elastic:
    name: elastic
